export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST';
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL = 'GROUP_LIST_FAIL';
export const GROUP_LIST_RESET = 'GROUP_LIST_RESET';

export const GROUP_ADD_NEW_REQUEST = 'GROUP_ADD_NEW_REQUEST';
export const GROUP_ADD_NEW_SUCCESS = 'GROUP_ADD_NEW_SUCCESS';
export const GROUP_ADD_NEW_FAIL = 'GROUP_ADD_NEW_FAIL';
export const GROUP_ADD_NEW_RESET = 'GROUP_ADD_NEW_RESET';

export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST';
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS';
export const GROUP_DELETE_FAIL = 'GROUP_DELETE_FAIL';

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS';
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL';
export const GROUP_DETAILS_RESET = 'GROUP_DETAILS_RESET';

export const GROUP_UPDATE_REQUEST = 'GROUP_UPDATE_REQUEST';
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS';
export const GROUP_UPDATE_FAIL = 'GROUP_UPDATE_FAIL';
export const GROUP_UPDATE_RESET = 'GROUP_UPDATE_RESET';