# Generated by Django 4.0 on 2021-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
